### PR TITLE
Add io.quarkiverse.hibernate.types.util.CamelCaseToSnakeCaseNamingStrategy

### LINKED ISSUE #5: Add CamelCaseToSnakeCasePhysicalNamingStrategy
This class from the hibernate-types library is really useful and it would be great to have it included in this extension

### PR DESCRIPTION
**Pull request by gastaldi**
Fixes #5

### CODE REVIEW

**Comment by andrejpetras** [comment]
@gastaldi 
how can we configure the naming strategy in Quarkus?
I did not find the property `hibernate.physical_naming_strategy` only for the `xml` configuration.
https://github.com/quarkusio/quarkus/blob/e61ad1c14b2c8a1c059afefb9be02e29d5d56292/extensions/hibernate-reactive/deployment/src/main/java/io/quarkus/hibernate/reactive/deployment/HibernateReactiveProcessor.java#L239

Source:
https://vladmihalcea.com/map-camel-case-properties-snake-case-column-names-hibernate/

In order to use the CamelCaseToSnakeCaseNamingStrategy custom naming strategy, you need to supply it to Hibernate via the hibernate.physical_naming_strategy configuration property:
```
<property name="hibernate.physical_naming_strategy" value="com.vladmihalcea.hibernate.naming.CamelCaseToSnakeCaseNamingStrategy"/>
```

**Comment by gastaldi** [comment]
@andrejpetras not sure that works in hibernate-reactive, but here is an example on how to set it using the regular hibernate-orm extension: https://github.com/quarkusio/registry.quarkus.io/blob/main/src/main/resources/application.properties#L4

**Comment by gastaldi** [comment]
I wonder if we precompile the patterns would be faster here

**Comment by gsmet** [comment]
@gastaldi yes, please compile the patterns and make them static.

**Comment by gastaldi** [comment]
> @gastaldi yes, please compile the patterns and make them static.

Done

**Pull request merged**
